#!/usr/bin/python

# USAGE:
# chmod +x forever
# ./forever neuromax.py

# to stop it:
# add alias kp='killall -v python neuromax.py'
# to bashrc, then type kp, (or just run killall -v python neuromax.py)

from subprocess import Popen
import sys

filename = sys.argv[1]
while True:
    print("\nStarting " + filename)
    p = Popen("python " + filename, shell=True)
    p.wait()
