#!/usr/bin/python

# USAGE:
# chmod +x forever
# ./forever neuromax.py

from subprocess import Popen
import sys

filename = sys.argv[1]
while True:
    print("\nStarting " + filename)
    p = Popen("python " + filename, shell=True)
    p.wait()
